name: PrisonMaden
version: '1.0.0'
main: com.prisonmaden.core.PrisonMaden
api-version: '1.21'
author: PrisonMaden
description: Kisisel Prison maden dunyasi, GUI menuler ve kazma yukseltme sistemi
softdepend: [Multiverse-Core]

commands:
  maden:
    description: Kisisel maden dunyani yonetir
    usage: /maden [ayarlar|sil]
  madenziyaret:
    description: Baska bir oyuncunun madenini ziyaret et
    usage: /madenziyaret <oyuncu>

permissions:
  prisonmaden.kullan:
    description: Maden komutlarini kullanabilir
    default: true
